import Head from "next/head";
import Image from "next/image";
import { createGraphiQLFetcher } from "@graphiql/toolkit";
import { GraphiQL } from "graphiql";
import { useEffect, useState } from "react";

import styles from "../styles/Home.module.css";

// Default GraphQL query shown in the GraphiQL editor
const defaultQuery = /* GraphQL */ `
  {
    gitHubStatus {
      status {
        indicator
        description
      }
    }
  }
`;

export default function Home() {
  const [fetcher, setFetcher] = useState();

  useEffect(() => {
    // Use the GraphQL endpoint from environment variable or fallback to local path
    const graphqlUrl = process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || "/api/graphql";
    setFetcher(() => createGraphiQLFetcher({ url: graphqlUrl }));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          <a
            href="https://stepzen.com?utm_source=stepzen-vercel-starter-template"
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              alt="StepZen"
              height="36"
              width="144"
              src="//stepzen.com/images/logo.svg"
            />
          </a>
        </p>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        {fetcher ? (
          <div
            style={{
              width: "100%",
              maxWidth: "1233px",
              height: "370px",
            }}
          >
            <GraphiQL fetcher={fetcher} defaultQuery={defaultQuery} />
          </div>
        ) : null}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
